# Generated by Django 5.1.5 on 2025-02-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='events/'),
        ),
    ]
