# Generated by Django 5.1.5 on 2025-02-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='events/'),
        ),
    ]
